# Redis config
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  secretttl: 200

# secrettypes: customsecret, randomstring, sshkeypair
secrettype:
  randomstring:
    secretlength: 20
    secretiscomplex: "false"
    comment: ""
    email: ""
  sshkeypair:
    keytype: "DSA"
    keylength: 2048
    keycomment: "paul@example.com"
    keypassphrase: ""
    public_key: ""
    private_key: ""
    encrypted_private_key: ""
    comment: ""
    email: ""
  customsecret:
    secret: ""
    comment: ""
    email: ""

# Ruby Pony Gem :via_options (https://github.com/benprew/pony)
#
# smtp:
#   address: 'smtp.gmail.com',
#   port: '587',
#   enable_starttls_auto: true,
#   user_name: 'user',
#   password: 'password_see_note',
#   authentication: :plain, # :plain, :login, :cram_md5, no auth by default
#   domain: "localhost.localdomain" # the HELO domain provided by the client to the server
#
smtp:
  address: localhost
  port: 25
  username: ""
  password: ""
  from: onetimesecret@example.com
